import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { END } from "redux-saga";
import {StoreWrapper} from "../store";
import React from "react";
import {NextPage} from "next";
import {connect} from "react-redux";
import { AddressActions } from "../store/modules/adress";


// @ts-ignore
export const getServerSideProps = StoreWrapper.getServerSideProps(store =>  async (context) => {
    store.dispatch(AddressActions.GetAddressInfoInit({ address: 'Hello'}))
})

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}


export default connect((state:any) => state)(Home);