import { NextPage } from "next";
// import Head from "next/head";
import React from "react";
import { StoreWrapper } from "../store";
import { AddressActions } from "../store/modules/adress";
// import styles from "../../styles/Home.module.css";
// import { HomePageProps } from "./types";

export const getServerSideProps = StoreWrapper.getServerSideProps(
  (store) => async (context) => {
    store.dispatch(
      AddressActions.GetAddressInfoInit({
        address: "8PdqmeKdn3999sT3jkkx3JRquGqZAfr3m7F4G5NoWkuG",
      })
    );
  }
);

const IndexPage: NextPage = () => (
  <>
    {/* <Head> */}
    {/* <title>Create Next App</title> */}
    {/* <meta name="description" content="Generated by create next app" /> */}
    {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
    {/* <link rel="icon" href="/favicon.ico" /> */}
    {/* </Head> */}
    <main />
  </>
);

export default IndexPage;
