import { NextPage } from "next";
// import Head from "next/head";
import React from "react";
import { END } from "redux-saga";
import { SeacrhBlock } from "../components/SearchBlock";
import { StoreWrapper } from "../store";
import { NftsAddressesSliceActions } from "../store/modules/NftsAdresses";
// import styles from "../../styles/Home.module.css";
// import { HomePageProps } from "./types";

export const getServerSideProps = StoreWrapper.getServerSideProps(
  (store) => async (context) => {
    store.dispatch(
      NftsAddressesSliceActions.GetNftsAddressesInfoInit({
        address: "8PdqmeKdn3999sT3jkkx3JRquGqZAfr3m7F4G5NoWkuG",
      })
    );

    store.dispatch(END);
    await store.sagaTask.toPromise();
  }
);

const IndexPage: NextPage = () => (
  <>
    {/* <Head> */}
    {/* <title>Create Next App</title> */}
    {/* <meta name="description" content="Generated by create next app" /> */}
    {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
    {/* <link rel="icon" href="/favicon.ico" /> */}
    {/* </Head> */}
    <main>
      <SeacrhBlock />
    </main>
  </>
);

export default IndexPage;
